<a href="https://colab.research.google.com/github/KiloDragon/HWinn/blob/main/HW4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Задача 1

In [ ]:
import numpy as np

A = np.array([[1,2,1],[-2,1,1]])
B = np.array([[3,1],[-1,0],[2,4]])
C = np.array([[-2,2],[1,-1],[1,2]])
print(f'Матрица A :{A}')
print(f'Матрица B :{B}')
print(f'Матрица C :{C}')



Матрица A :[[ 1  2  1]
 [-2  1  1]]
Матрица B :[[ 3  1]
 [-1  0]
 [ 2  4]]
Матрица C :[[-2  2]
 [ 1 -1]
 [ 1  2]]


"sum1 = A+2B"
"sum2 = B+2C"

In [ ]:
def matrix_sum(matrix1,matrix2):
 if matrix1.shape == matrix2.shape:
   return np.add(matrix1,2*matrix2)
 else:
   return"Матрицы разной формы складывать нельзя"



In [ ]:
print(matrix_sum(A,B))
print(matrix_sum(B,C))

Матрицы разной формы складывать нельзя
[[-1  5]
 [ 1 -2]
 [ 4  8]]


Задача 2


In [ ]:
matrix_init=np.zeros((8,8),dtype=np.int32)
matrix_init[::] = [1,0,1,0,1,0,1,0]
matrix_init[::2] = [0,1,0,1,0,1,0,1]
matrix_init

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]], dtype=int32)

Задача 3

In [ ]:
vector_1=np.arange(0,1.5,0.1)
print(vector_1)
vector_2=np.arange(1,7,1)
print(vector_2)


[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4]
[1 2 3 4 5 6]


In [ ]:
new_vector_1=np.reshape(vector_1,(5,3))
new_vector_2=np.reshape(vector_2,(3,2))
print(new_vector_1)
print(new_vector_2)

[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]
 [0.9 1.  1.1]
 [1.2 1.3 1.4]]
[[1 2]
 [3 4]
 [5 6]]


In [ ]:
result=np.dot(new_vector_1,new_vector_2)
result

array([[ 1.3,  1.6],
       [ 4. ,  5.2],
       [ 6.7,  8.8],
       [ 9.4, 12.4],
       [12.1, 16. ]])

Задача 4

In [ ]:
vector_3=np.arange(1,37,1,dtype=np.int32)
new_vector_3 = []
for i in vector_3:
   if i % 3 == 0:
      new_vector_3.append(i)
print(new_vector_3)
print(vector_3)

[3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]
